name: MovecraftUnloading
main: io.github.cccm5.Main
version: 1.0.0
depend: [Movecraft, Vault, Citizens, dtlCore, dtlTraders]
commands:
    load:
        description: loads cargo
    unload:
        description: unloads cargo
    cargo:
        description: get information about the plugin